### ISSUE TITLE
Nič se ne dogaja

### ISSUE THREAD

**Issue by matijapretnar** [nastja88/projekt_MZR#1]
Ker bodo v kratkem kratke predstavitve, čimprej začnite z delom na projektu. Na spletni učilnici sem [objavil navodila](https://ucilnica.fmf.uni-lj.si/mod/forum/discuss.php?d=15136), kako začeti.

**Comment by nastja88** [comment]
@matijapretnar sedaj sem nekako naredila tisto, kar sem imela v načrtu za kratko predstavitev. Zanima me ali je trenuten program ustrezen, ali bi morala še kaj dodati ali izboljšati. Ali je trenutna časovna zahtevnost ustrezna (sicer nimam več ideje, kako bi jo lahko izboljšala, brez da zmanjšam število ponovitev v simulaciji)?

**Comment by matijapretnar** [comment]
Pozdravljeni, programa mi ne uspe zagnati, ker dobim napako `Object 'spomini` not found`. Kot gledam, je nikjer ne definirate.

Sicer mislim, da bi za kratko predstavitev moralo biti dovolj gradiva.

Glede časovne zahtevnosti moram najprej preizkusiti, da vidim, kakšna je. Včasih je velika zahtevnost neizogibna - v tem primeru bi bilo dobro, da se da rezultate simulacije tudi shraniti in kasneje ponovno naložiti. Bom o tem malo več napisal tudi na spletni učilnici.

**Comment by nastja88** [comment]
@matijapretnar hvala za odgovor. Sedaj bi program moral delovati.

**Comment by matijapretnar** [comment]
Ja, dela.
