### ISSUE TITLE
Smiselnost simulacije

### ISSUE THREAD

**Issue by matijapretnar** [nastja88/projekt_MZR#2]
Če igralcu 1 spomin nastavim na 0, igralcu 2 pa na 1, je verjetnost zmage obeh igralcev približno enaka. Ali je to smiselno?
<img width="1022" alt="Screenshot 2020-04-02 at 13 59 33" src="https://user-images.githubusercontent.com/1502128/78246890-2f1fbd80-74ea-11ea-9471-78788f684f0a.png">

**Comment by nastja88** [comment]
Sem popravila, hvala za opozorilo.

**Comment by matijapretnar** [comment]
Ja, to je zdaj videti smiselno.
