### ISSUE TITLE
Prikaz trenutnega napredka simulacije skupaj z paralelnim računanjem

### ISSUE THREAD

**Issue by nastja88** [nastja88/projekt_MZR#3]
Pozdravljeni!

Težave imam s prikazom trenutnega napredka simulacije skupaj z paralelnim računanjem. V ta namen sem za nekaj poskusov rešitve problema ustvarila novo vejo `brez_paralelnega`, v kateri se nahajata spodaj omenjeni datoteki. 

Brez uporabe paralelnega računanja prikaz napredka ni bil težaven (tega sem implementirala v datoteki `shiny.r` na veji `brez_paralelnega`. Toda s tem se pri določenih kombinacijah nastavitev parametrov (večje število igralcev, večje velikosti skupin, slabši spomin igralcev, večje število ponovitev igre) trajanje simulacije močno podaljša.

Kot sem omenila že zgoraj je težavna kombinacija prikaza trenutnega napredka simulacije skupaj z paralelnim računanjem. V skladu z informacijo na [povezavi](https://stackoverflow.com/questions/40684721/how-to-show-the-progress-of-code-in-parallel-computation-in-r?noredirect=1&lq=1) sem namesto knjižnice `doParallel` uporabila `doSNOW`. Nato sem po [viru](https://stackoverflow.com/questions/54532486/using-standard-r-shiny-progress-bar-in-parallel-foreach-calculations?rq=1) ugotovila, da ne morem uporabiti funkcije `withProgress` skupaj z `foreach` in po istem viru za prikaz trenutnega napredka raje uporabila knjižnice `futures`, `promises` in `ipc`. Pri tem sem si pomagala z nasveti na [povezavi](https://cran.r-project.org/web/packages/promises/vignettes/intro.html), a mi program vrne napako `Don't know how to convert object of class NULL into a promise`. Ta poskus rešitve se nahaja v datoteki `shiny1.r` na veji `brez_paralelnega`.

Imate morda vi kakšno idejo, kako naj rešim zgornji problem? Ali naj ostanem kar pri verziji brez paralelnega izvajanja?

Hvala za pomoč,
Nastja

**Comment by nastja88** [comment]
@jO-Osko @matijapretnar

**Comment by matijapretnar** [comment]
Aha, bom pogledal v kratkem, kaj se dogaja.

**Comment by matijapretnar** [comment]
Kot sam poizkušam, stvari na veji `master` delujejo čisto dovolj hitro, tako da ne vem, ali je vredno poizkušati paralelno računanje, sploh, ker ga R ne podpira preveč dobro. Morda lahko kvečjemu pri dalj časa trajajočih simulacijah sproti posodabljate graf verjetnosti?
